app/gotwork/gotwork/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jobs.urls'))
]

app/gotwork/jobs/urls.py
from django.urls import path, include
from . import views

app_name = 'jobs'
urlpatterns = [
    path('', views.frontPage, name='frontPage'),
    path('sign_up/generic', views.genericSignUp, name='genericSignUp'),
    path('sign_up/worker', views.workerSignUp, name='workerSignUp'),
    path('sign_up/customer', views.customerSignUp, name='customerSignUp'),

    path('user/', views.userHome, name="userHome"),
    path('worker/', views.workerHome, name='workerHome'), #URL Format: hostname/worker/<worker_id>/
    path('accept/<int:job_id>/<int:worker_id>/', views.acceptJob, name='acceptJob'), #URL Format: hostname/<job_id>/<worker_id>/ #For post requests
    path('finish/<int:job_id>/', views.finishJob, name='finishJob'), #URL Format: hostname/<job_id>/<worker_id>/ #For post requests
    
    path('customer/', views.customerHome, name='customerHome'), #URL Format: hostname/worker/<worker_id>/
    path('delete/<int:job_id>/', views.deleteJob, name='deleteJob'), #URL Format: hostname/<job_id>/ #For post requests
    path('createjob/<int:customer_id>/', views.createJob, name='createJob'),
    path('createjob/<int:customer_id>/<str:error>/', views.createJob, name='createJob'),
    path('createjobtype/<int:owner_id>/', views.createJobType, name='createJobType'),
    path('createjobtype/<int:owner_id>/<str:error>/', views.createJobType, name='createJobType'),
    path('save_job/<int:customer_id>/', views.saveJob, name='saveJob'),
    path('save_job_type/<int:owner_id>/', views.saveJobType, name='saveJobType'),
    path('reviewworker/<int:job_id>/', views.reviewWorker, name='reviewWorker'),
    path('approvedenyrequest/<int:request_id>/<int:owner_id>/', views.approveDenyRequest, name='approveDenyRequest'),

    path('owner/<str:message>/', views.ownerHome, name='ownerHome'),
    path('owner/', views.ownerHome, name='ownerHome'),
    
    path('worker/<int:worker_id>/settings', views.workerSettings, name='workerSettings'),
    path('customer/<int:customer_id>/settings', views.customerSettings, name='customerSettings'),
    path('owner/<int:owner_id>/settings', views.ownerSettings, name='ownerSettings'),

    path('postworkersettings/<int:worker_id>/', views.postWorkerSettings, name='postWorkerSettings'),
    path('postcustomersettings/<int:customer_id>/', views.postCustomerSettings, name='postCustomerSettings'),
    path('postownersettings/<int:owner_id>/', views.postOwnerSettings, name='postOwnerSettings'),

    path('deposit/worker/<int:user_id>/', views.depositWorker, name='depositWorker'),
    path('withdraw/worker/<int:user_id>/', views.withdrawWorker, name='withdrawWorker'),
    path('deposit/customer/<int:user_id>/', views.depositCustomer, name='depositCustomer'),
    path('withdraw/customer/<int:user_id>/', views.withdrawCustomer, name='withdrawCustomer'),
    path('deposit/owner/<int:user_id>/', views.depositOwner, name='depositOwner'),
    path('withdraw/owner/<int:user_id>/', views.withdrawOwner, name='withdrawOwner'),
    
    path('utilitytestworker/<int:worker_id>/', views.utilityTestWorker, name='utilityTestWorker'),
    path('utilitytestcustomer/<int:customer_id>/', views.utilityTestCustomer, name='utilityTestCustomer'),
    # path('get_active_jobs', views.get_active_jobs, name="get_active_jobs"), #URL Format: hostname/get_active_jobs?id=USER_ID
    path('customer_sign_up', views.postCustomer, name='postCustomer'),
    path('worker_sign_up', views.createWorker, name='createWorker'),
    path('front_page', views.logIn, name='logIn'),

    path('logout/', views.Logout, name="logout")
]

app/gotwork/jobs/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from json import dumps
from jobs.utility import *
from django.contrib.auth import get_user_model
import logging

from jobs.models import Job, Worker, Customer, Owner



def frontPage(request):
    return render(request, 'jobs/front_page.html')

def genericSignUp(request):
    return render(request, 'jobs/generic_sign_up.html')


def workerSignUp(request):
    return render(request, 'jobs/worker_sign_up.html')

def customerSignUp(request):
    return render(request, 'jobs/customer_sign_up.html')

def userHome(request):
    if not request.user.is_authenticated:
        return render(request, 'jobs/login_error.html')
    user = CustomUser.objects.get(id=request.user.id)
    if user.accountType == 'W':
        return HttpResponseRedirect(reverse('jobs:workerHome'))
    elif user.accountType == 'C':
        return HttpResponseRedirect(reverse('jobs:customerHome'))
    elif user.accountType == 'O':
        return HttpResponseRedirect(reverse('jobs:ownerHome', args=(" ")))
    else:
        return HttpResponseRedirect(reverse('jobs:frontPage'))



def workerHome(request):
    if not request.user.is_authenticated or request.user.accountType != 'W':
        return render(request, 'jobs/login_error.html')
    print(request.user.accountType)
    worker = Worker.objects.get(id=request.user.id)

    available_jobs = GetWorkerPendingJobs(request.user.id)
    active_jobs = GetWorkerActiveAndDueJobs(request.user.id)
    disputed_jobs = GetWorkerDisputedJobs(request.user.id)
    context = {
        'available_jobs' : available_jobs,
        'worker' : worker,
        'active_jobs' : active_jobs,
        'disputed_jobs' : disputed_jobs,
    }
    return render(request, 'jobs/worker_home.html', context)

def customerHome(request):
    if not request.user.is_authenticated or request.user.accountType != 'C':
        return render(request, 'jobs/login_error.html')
    customer = Customer.objects.get(id=request.user.id)
    active_jobs = GetCustomerActiveJobs(request.user.id)
    pending_jobs = GetCustomerPendingJobs(request.user.id)
    finished_jobs = GetCustomerFinishedJobs(request.user.id)
    
    context = {
        'customer' : customer,
        'active_jobs' : active_jobs,
        'pending_jobs' : pending_jobs,
        'finished_jobs' : finished_jobs,
    }

    return render(request, 'jobs/customer_home.html', context)

def ownerHome(request, message=" "):
    if not request.user.is_authenticated or request.user.accountType != 'O':
        return render(request, 'jobs/login_error.html')
    owner = Owner.objects.get(id=request.user.id)
    # TODO: How do we want to handle refund requests?
    refund_requests = RefundRequest.objects.all()

    context = {
        'owner' : owner,
        'refund_requests' : refund_requests,
        'message' : message,
    }

    return render(request, 'jobs/owner_home.html', context)

def acceptJob(request, job_id, worker_id):
    job = get_object_or_404(Job, pk=job_id)
    worker = get_object_or_404(Worker, pk=worker_id)
    print("worker " + str(worker_id) + " accepted job " + str(job_id))
    AcceptJob(worker_id, job_id)
    #send back to worker home
    return HttpResponseRedirect(reverse('jobs:workerHome'))

def finishJob(request, job_id):
    job = get_object_or_404(Job, pk=job_id)
    customer = job.customer
    worker = job.worker
    completionTime = request.POST["timetaken"]
    print("worker" + str(worker.id) + " finished job " + str(job_id))
    FinishJob(job_id) #customer parameter?
    AddCompletionTime(job_id, completionTime)
    # Update the customer's ratings
    rating = request.POST["review"]
    # If thumbs up then rating is 10, if thumbs down then rating is 0
    ratingNum = 0
    if (rating == "up"):
        ratingNum = 10
    UpdateCustomerRatings(customer.id, ratingNum)
    # Send back to worker home
    return HttpResponseRedirect(reverse('jobs:workerHome'))

def reviewWorker(request, job_id):
    job = get_object_or_404(Job, pk=job_id)
    customer = job.customer
    worker = job.worker
    # Update the worker's ratings
    rating = request.POST["review"]
    # If thumbs up then rating is 10, if thumbs down then rating is 0
    ratingNum = 0
    if (rating == "up"):
        ratingNum = 10
    UpdateWorkerRatings(worker.id, ratingNum)

    # If the user requested a refund, create a refund request
    try:
        reason = request.POST["reason"]
        if (reason and reason.strip()):
            refundRequest = RefundRequest.objects.create(job=job, description=reason)
            refundRequest.save()
            DisputeJob(job_id)
        else:
            SetJobAsReviewed(job_id)
    except:
        SetJobAsReviewed(job_id)

    # See if the user chose to blacklist the worker
    try:
        blacklist = request.POST["blacklist"]
        if (blacklist):
            print("Customer " + str(customer.id) + " blacklisted " + str(worker.id))
            BlacklistWorker(job_id)
    except:
        # Do nothing
        print()

    # Send back to customer home
    return HttpResponseRedirect(reverse('jobs:customerHome'))

def deleteJob(request, job_id):
    job = Job.objects.get(pk=job_id)
    job.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))  #  Redirects to previous page

def workerSettings(request, worker_id):
    user = get_object_or_404(Worker, pk=worker_id)
    job_types = GetAllJobTypes()
    fromTime = "07:00" #some default data to display
    toTime = "19:00" #some default data to display
    if len(user.availabletimes_set.all()) != 0:
        fromTime = str(user.availabletimes_set.all()[0].getFromTimeStr())
        toTime = str(user.availabletimes_set.all()[0].getToTimeStr())

    context = {
        'user' : user,
        'fromTime' : fromTime,
        'toTime' : toTime,
        'job_types' : job_types,
    }
    return render(request, 'jobs/worker_settings.html', context)

def customerSettings(request, customer_id):
    user = get_object_or_404(Customer, pk=customer_id)
    context = {
        'user' : user,
    }
    return render(request, 'jobs/customer_settings.html', context)

def ownerSettings(request, owner_id):
    user = get_object_or_404(Owner, pk=owner_id)
    context = {
        'user' : user,
    }
    return render(request, 'jobs/owner_settings.html', context)

def approveDenyRequest(request, request_id, owner_id):
    refundRequest = get_object_or_404(RefundRequest, pk=request_id)
    requestReview = request.POST.get("finished")

    owner = Owner.objects.get(id=owner_id)
    job = Job.objects.get(id=refundRequest.job.id)
    if (owner.balance < job.price / 10):
        print("Refund request cannot be accepted: insuficient funds")
        return HttpResponseRedirect(reverse('jobs:ownerHome', args=["Refund request cannot be accepted due to insufficient funds."]))
    else:

        # Refund money if request was accepted
        if (requestReview == "Accept"):
            RefundMoney(refundRequest.id)
        CloseRefundRequest(refundRequest.id)
        
        return HttpResponseRedirect(reverse('jobs:ownerHome', args=(" ")))

def postWorkerSettings(request, worker_id):
    worker = Worker.objects.get(pk=worker_id)
    first_name = request.POST["first_name"]
    last_name = request.POST["last_name"]
    email = request.POST["email"]
    zipCode = request.POST["zip"]
    distance = request.POST["distance"]
    fromTime = request.POST["starttime"]
    toTime = request.POST["endtime"]

    jobTypes = []
    for jobType in JobType.objects.all():
        if request.POST.get(jobType.jobType, '') == 'on':
            jobTypes.append(jobType)

    UpdateWorkerSettings(worker.id, first_name, last_name, email, zipCode, distance, jobTypes, fromTime, toTime)

    return HttpResponseRedirect(reverse('jobs:workerHome'))

def postCustomerSettings(request, customer_id):
    customer = Customer.objects.get(pk=customer_id)
    first_name = request.POST["first_name"]
    last_name = request.POST["last_name"]
    email = request.POST["email"]
    zipCode = request.POST["zip"]
    phoneNumber = request.POST["phone"]
    defaultAddress = request.POST["address"]

    UpdateCustomerSettings(customer.id, first_name, last_name, email, zipCode, phoneNumber, defaultAddress)

    return HttpResponseRedirect(reverse('jobs:customerHome'))


def postOwnerSettings(request, owner_id):
    owner = Owner.objects.get(pk=owner_id)
    first_name = request.POST["first_name"]
    last_name = request.POST["last_name"]
    email = request.POST["email"]
    zipCode = request.POST["zip"]

    UpdateOwnerSettings(owner.id, first_name, last_name, email, zipCode)

    return HttpResponseRedirect(reverse('jobs:ownerHome', args=(" ")))


#use utility? CustomUser needs to be abstract, it's causing problems that it has a place in the table.
def depositWorker(request, user_id):
    user = Worker.objects.get(id=user_id)
    amount = request.POST["amount"]
    try:
        user.balance += float(amount)
        user.save()
    except:
        print("amount provided could not be converted to a float")
    return HttpResponseRedirect(reverse('jobs:workerHome'))

def withdrawWorker(request, user_id):
    user = Worker.objects.get(id=user_id)
    amount = request.POST["amount"]
    try:
        if (user.balance - float(amount) >= 0.0):
            user.balance -= float(amount)
            user.save()
        else:
            print("cannot withdraw more than the amount avaialble")
            user.balance = 0
    except:
        print("amount provided could not be converted to a float")
    return HttpResponseRedirect(reverse('jobs:workerHome'))

def depositCustomer(request, user_id):
    user = Customer.objects.get(id=user_id)
    amount = request.POST["amount"]
    try:
        user.balance += float(amount)

app/gotwork/jobs/templates/jobs/customer_home.html
{% load static %}

<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <title>Customer Home</title>
    <link rel="shortcut icon" type="image/ico" href="{% static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'jobs/user_home_style.css' %}">
    <script src="https://unpkg.com/vue@next"></script>
</head>

<body>
    <div id="app">
        <div class="topbar">
            <span id="profile-icon">
                O-|-<
            </span>
            <span id="profile-name">
                {{ customer.first_name }} {{ customer.last_name }}
            </span>
            <form action="{% url 'jobs:logout' %}" method="post">
                {% csrf_token %}
                <input type="submit" class="logout-button" name="logout" id="logout" value="Logout">
            </form>
            <form action="{% url 'jobs:customerSettings' customer.id %}" method="get">
                <input type="submit" class="settings-button" name="customersettings" 
                    id="settings-button" value="Profile Settings" onclick="profileSettings(this)">
            </form>
            <form action="{% url 'jobs:createJob' customer.id %}" method="get">
                <input type="submit" class="create-job-button" id="create-job-button"
                value="Create New Job" name="createjob">
            </form>
        </div>

        <div class="sidebar">
            <h2>Account info:</h2>
            <p>Current Funds: {{ customer.balance|floatformat:2 }}</p>
        </div>
        
        <div class="main">
            <div class="finished-jobs">
                <h2>Finished Jobs</h2>
                {% for job in finished_jobs %}
                    <div class="job-detail">
                        <p>Type: {{ job.jobType }}</p>
                        <p onclick="showAddress(this)"> Location: {{ job.zipCode }}</p>
                        <p>Pay: ${{ job.price|floatformat:2 }}</p>
                        <p>Worker: {{ job.worker }}</p>
                        <p>Worker Contact: {{ job.worker.contact }}</p>
                        <p>Status: {{ job.status }}</p>
                        <p>Date: {{ job.getDueDatePretty }}</p>
                        <!-- This is the button to review a finished job. Once they click this, it will go away. 
                            If you choose to do front end, simply edit this. If you choose back-end implementation, wrap this in a <form> :)-->
                        <input type="button" name="review" id="review-button" class="review-button" value="Review Job" @click="showPopup()">
                    </div>
                    <div id="modal" class="modal">
                        <div class="modal-content">
                            <span class="close" @click="closePopup()">&times;</span>
                            <form action="{% url 'jobs:reviewWorker' job.id %}" method="post" style="border:initial;" id="parent">
                            {% csrf_token %}
                                <p style="font-size: 20px;">Did the worker do a good job?</p>
                                <label class="thumbs-up" @click="removeRefundRequest()">
                                    <input type="radio" name="review" value="up" required>
                                    <span class="thumbs">👍</span>
                                </label>
                                <label class="thumbs-down" @click="addRefundRequest()">
                                    <input type="radio" name="review" value="down" required>
                                    <span class="thumbs">👎</span>
                                </label>

                                <br id="break">
                                <input type="submit" name="finishedreview" class="job-button" id="finishedreview" value="Submit"/>
                            </form>
                        </div>
                    </div>
                {% empty %}
                    <div class="job-detail">
                        <p>You don't have any unreviewed finished jobs at the moment.</p>
                    </div>
                {% endfor %}
            </div>
            
            <div class="current-jobs">
                <h2>Active Jobs:</h2>
                <!--loop each current job-->
                {% for job in active_jobs %}
                    <div class="job-detail">
                        <p>Type: {{ job.jobType }}</p>
                        <p onclick="showAddress(this)"> Location: {{ job.zipCode }}</p>
                        <p>Pay: ${{ job.price|floatformat:2 }}</p>
                        <p>Worker: {{ job.worker }}</p>
                        <p>Worker Contact: {{ job.worker.contact }}</p>
                        <p>Status: {{ job.status }}</p>
                        <p>Date: {{ job.getDueDatePretty }}</p>
                    </div>
                {% empty %}
                    <div class="job-detail">
                        <p>You don't have any active jobs at the moment.</p>
                    </div>
                {% endfor %}
            </div>
            <div class="available-jobs">
                <h2>Available Jobs:</h2>
                {% for job in pending_jobs %}
                    <div class="job-detail">
                        <form action="{% url 'jobs:deleteJob' job.id %}" method="post">
                            {% csrf_token %}
                            <p>Type: {{ job.jobType }}</p> 
                            <p onclick="showAddress(this)">Location: {{ job.customer.zipCode }}</p>
                            <p>Pay: ${{ job.price|floatformat:2 }}</p> 
                            <p>Status: {{ job.status }}</p>
                            <p>Date: {{ job.getDueDatePretty }}</p>
                            <input type="submit" name="delete" class="job-button"
                            id="delete-button" value="Delete Job" onclick="deleteJob(this)">
                        </form>
                    </div>
                {% empty %}
                <div class="job-detail">
                    <p>You don't have any pending jobs. Feel free to create one!</p>
                </div>
                {% endfor %}
            </div>

        </div>
    </div>
    <script type="text/javascript" src="{% static 'jobs/js/customer_home.js' %}"></script>
</body>
<html>

app/gotwork/jobs/templates/jobs/front_page.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <link rel="stylesheet" href="{% static 'jobs/front_page_style.css' %}" type="text/css" >
        <title>Got Work?</title>
        <link rel="shortcut icon" type="image/ico" href="{% static 'favicon.ico' %}"/>
    </head>

    <body class="background">
        <script src="{% static 'jobs/js/front_page.js' %}"></script>

        <div>
            <header class="header center">
                <h1>Got Work?</h1>
            </header>
            <div class="center" style="padding: 10px;"></div>
            <h2 class="tagline center">We Do, So You Don't Have To</h2>
        </div>

        <div class="sign-up">
            <h2 class="other-text center" style="font-size: 32px;">Click Below To Create An Account</h2>
            <div class="center">
                <button class="center">
                    <a href="{% url 'jobs:genericSignUp' %}" style="text-decoration: none; color: black;">
                        Sign Up
                    </a>
                </button>
            </div>
        </div>

        <div class="login">
            <h2 class="other-text center" style="font-size: 32px;">Already Have An Account? Sign In Below</h2>
            <form action="{% url 'jobs:logIn' %}" method="post">
                {% csrf_token %}
                <div class="form-spacing center">
                    <input type="text" id="username" name="username" placeholder="Username" class="form-input" />
                </div>

                <div class="form-spacing center">
                    <input type="password" id="password" name="password" placeholder="Password" class="form-input" />
                </div>

                <div class="center" style="padding: 15px; padding-bottom: 150px;">
                    <button class="center" type="submit">Login</button>
                </div>
            </form>
        </div>
    </body>
</html>

app/gotwork/jobs/templates/jobs/login_error.html
{% load static %}

<meta charset="utf-8">
<head>
    <title>Create Job</title>
    <link rel="shortcut icon" type="image/ico" href="{% static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'jobs/settings_style.css' %}">
    <script src="https://unpkg.com/vue@next"></script>
</head>

<body>
    <p>Yo you can't access this page...</p>
</body>
</html>

app/gotwork/jobs/templates/jobs/owner_home.html
{% load static %}

<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <title>Owner Home</title>
    <link rel="shortcut icon" type="image/ico" href="{% static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'jobs/user_home_style.css' %}">
    <script src="https://unpkg.com/vue@next"></script>
</head>

<body>
    <div id="app">
        <div class="topbar">
            <span id="profile-icon">
                O-|-<
            </span>
            <span id="profile-name">
                {{ owner.first_name }} {{ owner.last_name }}
            </span>
            <form action="{% url 'jobs:logout' %}" method="post">
                {% csrf_token %}
                <input type="submit" class="logout-button" name="logout" id="logout" value="Logout">
            </form>
            <form action="{% url 'jobs:ownerSettings' owner.id %}" method="get">
                <input type="submit" class="settings-button" name="ownersettings" 
                    id="settings-button" value="Profile Settings" onclick="profileSettings(this)">
            </form>
            <form action="{% url 'jobs:createJobType' owner.id %}" method="get">
                <input type="submit" class="create-job-type-button" id="create-job-type-button"
                value="Create New Job Type" name="createjobtype">
            </form>
        </div>
        <div class="sidebar">
            <h2>Account info:</h2>
            <p>Current Funds: {{ owner.balance|floatformat:2 }}</p>
        </div>
        <div class="main">
            {% if message != " " %}
                <p class="error-message"> {{message}} </p>
            {% endif %}
            <div class="current-jobs">
                <h2>Current Refund Requests:</h2>
                <!-- loop each refund request -->
                {% for request in refund_requests %}
                    <form class="job-detail" action="{% url 'jobs:approveDenyRequest' request.id owner.id %}" method="post">
                        {% csrf_token %}
                        <p>Refund Price: ${{ request.job.price|floatformat:2 }}</p>
                        <p>Customer: {{ request.job.customer.first_name }} {{ request.job.customer.last_name }}</p>
                        <p>Worker: {{ request.job.worker.first_name }} {{ request.job.worker.last_name }}</p>
                        <p>Request Reason: {{ request.description }}</p>
                        <input type="submit" name="finished" 
                        class="job-button" id="finished-button" value="Accept"
                        @click="acceptRequest(this)">
                        <input type="submit" name="finished" 
                        class="job-button" id="finished-button" value="Deny"
                        @click="denyRequest(this)">
                    </form>
                {% empty %}
                    <div class="job-detail">
                        <p>There aren't currently any refund requests.</p>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <script type="text/javascript" src="{% static 'jobs/js/worker_home.js' %}"></script>
</body>
<html>

app/gotwork/jobs/templates/jobs/worker_home.html
{% load static %}

<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <title>Worker Home</title>
    <link rel="shortcut icon" type="image/ico" href="{% static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'jobs/user_home_style.css' %}">
    <script src="https://unpkg.com/vue@next"></script>
</head>

<body>
    <div id="app">
        <div class="topbar">
            <span id="profile-icon">
                O-|-<
            </span>
            <span id="profile-name">
                {{ worker.first_name }} {{ worker.last_name }}
            </span>
            <form action="{% url 'jobs:logout' %}" method="post">
                {% csrf_token %}
                <input type="submit" class="logout-button" name="logout" id="logout" value="Logout">
            </form>
            <form action="{% url 'jobs:workerSettings' worker.id %}" method="get">
                <input type="submit" class="settings-button" name="workersettings" 
                    id="settings-button" value="Profile Settings" onclick="profileSettings(this)">
            </form>

        </div>
        <div class="sidebar">
            <h2>Account info:</h2>
            <p>Current Funds: {{ worker.balance|floatformat:2 }}</p>
        </div>
        <div class="main">
            {% if disputed_jobs.count != 0 %}
                <div class="disputed-jobs">
                <h2>Disputed Jobs:</h2>
                <p>The following jobs have been disputed by the client. Please contact the client to find out why.</p>
                {% for job in disputed_jobs %}
                    <div class="job-detail">
                        <p>Type: {{ job.jobType }}</p>
                        <p onclick="showAddress(this)"> Location: {{ job.zipCode }}</p>
                        <p>Pay: ${{ job.price|floatformat:2 }}</p>
                        <p>Worker: {{ job.worker }}</p>
                        <p>Worker Contact: {{ job.worker.contact }}</p>
                        <p>Status: {{ job.status }}</p>
                        <p>Date: {{ job.getDueDatePretty }}</p>
                    </div>
                {% endfor %}
                </div>
            {% endif %}
            <div class="current-jobs">
                <h2>Current Jobs:</h2>
                <!--loop each current job-->
                {% for job in active_jobs %}
                    <div class="job-detail">
                        <form>
                        {% csrf_token %}
                            <p>Type: {{ job.jobType }}</p>
                            <p onclick="showAddress(this)">Location: {{ job.customer.zipCode }}</p>
                            <p>Pay: ${{ job.price|floatformat:2 }}</p>
                            <p>Status: {{ job.status }}</p>
                            <p>Date: {{ job.getDueDatePretty }}</p>
                            <p>Customer Contact: {{ job.customer.email }}</p>
                            <input type="button" name="finished" 
                            class="job-button" id="finished-button" value="Finished!"
                            @click="showPopup()">
                        </form>
                    </div>
                    <div id="modal" class="modal">
                        <div class="modal-content">
                            <span class="close" @click="closePopup()">&times;</span>
                            <form action="{% url 'jobs:finishJob' job.id %}" method="post">
                            {% csrf_token %}
                                <p style="font-size: 20px;">How did the job go?</p>
                                <label class="thumbs-up">
                                    <input type="radio" name="review" value="up" required>
                                    <span class="thumbs">👍</span>
                                </label>
                                <label class="thumbs-down">
                                    <input type="radio" name="review" value="down" required>
                                    <span class="thumbs">👎</span>
                                </label>
        
                                <p style="font-size: 20px; padding-top: 50px;">How long did the job take to complete (in hours)?</p>
                                <input type="number" name="timetaken" id="timetaken" min="0" placeholder="Hours" required />
        
                                <br>
                                <input type="submit" name="finishedreview" class="job-button" id="finishedreview" value="Submit"/>
                            </form>
                        </div>
                    </div>
                {% empty %}
                    <div class="job-detail">
                        <p>You are't currently working any jobs.</p>
                    </div>
                {% endfor %}
            </div>
            <div class="available-jobs">
                <h2>Available Jobs:</h2>
                {% for job in available_jobs %}
                    <div class="job-detail">
                        <form action="{% url 'jobs:acceptJob' job.id worker.id %}" method="post">
                            {% csrf_token %}
                            <p>Type: {{ job.jobType }}</p> 
                            <p onclick="showAddress(this)">Location: {{ job.zipCode }}</p>
                            <p>Pay: ${{ job.price|floatformat:2 }}</p> 
                            <p>Status: {{ job.status }}</p>
                            <p>Date: {{ job.getDueDatePretty }}</p>
                            <input type="submit" name="accept" class="job-button"
                            id="accept-button" value="Accept Job" onclick="acceptJob(this)">
                        </form>
                    </div>
                {% empty %}
                <div class="job-detail">
                    <p>There aren't any available jobs at the moment. Please check again later.</p>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <script type="text/javascript" src="{% static 'jobs/js/worker_home.js' %}"></script>
</body>
<html>